(() => {
  const S = HabitStore, view = document.querySelector('#view'), notice = document.querySelector('#notice');
  let state = S.load(localStorage), tab = 'weekly', cursor = new Date(), selectedRecipeId = null, selectedMonthlyId = null;
  if (!Array.isArray(state.dailyGoalTemplates)) { const legacy = state.dailyGoals || {}; state.dailyGoalTemplates = []; state.dailyGoalChecks = {}; Object.entries(legacy).forEach(([day, goals]) => (goals || []).forEach(goal => { let template = state.dailyGoalTemplates.find(item => item.name === goal.name); if (!template) { template = { id: goal.id, name: goal.name, labels: goal.labels || [] }; state.dailyGoalTemplates.push(template); } (state.dailyGoalChecks[day] ||= {})[template.id] = goal.circles || template.labels.map(() => false); })); }
  state.dailyGoalChecks ||= {};
  let nextId = 0;
  const id = () => `item-${Date.now()}-${++nextId}-${Math.random().toString(16).slice(2)}`;
  const esc = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[char]);
  const save = () => { try { S.save(localStorage, state); return true; } catch (error) { show(`没有保存成功：${error.message}`); return false; } };
  const show = message => { notice.textContent = message; setTimeout(() => { if (notice.textContent === message) notice.textContent = ''; }, 3500); };
  const dateLabel = date => date.toLocaleDateString('zh-CN', { year:'numeric', month:'long', day:'numeric', weekday:'short' });
  function syncDailyGoalView(day) { state.dailyGoals ||= {}; state.dailyGoals[day] = state.dailyGoalTemplates.map(goal => ({ ...goal, circles: state.dailyGoalChecks[day]?.[goal.id] || goal.labels.map(() => false) })); }
  function changeTab(next) { tab = next; render(); }
  const nav = document.querySelector('nav'), navOrderKey = 'my-planner-nav-order';
  function restoreNavOrder() { try { const order = JSON.parse(localStorage.getItem(navOrderKey) || '[]'); if (!Array.isArray(order)) return; order.forEach(name => { const button = nav.querySelector(`[data-tab="${name}"]`); if (button) nav.append(button); }); } catch (_) {} }
  function saveNavOrder() { localStorage.setItem(navOrderKey, JSON.stringify([...nav.querySelectorAll('[data-tab]')].map(button => button.dataset.tab))); }
  function toolbar(title, before, after, clearSection, noPager = false) { return `<div class="toolbar">${noPager ? '' : '<button data-action="prev">←</button>'}<h2>${title}</h2>${noPager ? '' : '<button data-action="next">→</button>'}${before || ''}${after || ''}<button data-action="clear" data-clear="${clearSection}">清空本页数据</button></div>`; }
  function controls(item, attrs = '') { return `<button class="circle ${item.completed ? 'done':''}" data-action="toggle" ${attrs}>${item.completed ? '✓':''}</button><span class="name">${esc(item.name)}</span><button class="icon" title="编辑" data-action="edit" ${attrs}>✎</button><button class="icon" title="上移" data-action="up" ${attrs}>↑</button><button class="icon" title="下移" data-action="down" ${attrs}>↓</button><button class="icon" title="删除" data-action="delete" ${attrs}>×</button>`; }
  function list(items, attrs) { return items.length ? `<ul class="list">${items.map(item => `<li class="row ${item.completed?'done':''}" ${attrs} data-id="${item.id}"><span class="drag" draggable="true">⠿</span>${controls(item, `${attrs} data-id="${item.id}"`)}</li>`).join('')}</ul>` : '<p class="empty">这里还是空的。</p>'; }
  function renderWeekly() { const dates = S.weekDates(cursor), week = state.weekly; return `<div class="content">${toolbar(`${S.dateKey(dates[0])} ～ ${S.dateKey(dates[6])}`, '', '<button data-action="add-habit">新增习惯</button>', 'weekly')}<table class="grid"><thead><tr><th>习惯</th>${dates.map(date => `<th>${['一','二','三','四','五','六','日'][dates.indexOf(date)]}<br>${date.getDate()}</th>`).join('')}</tr></thead><tbody>${week.habits.map(habit => `<tr draggable="true" data-weekly-id="${habit.id}"><td><span class="drag">⠿</span> <span class="habit-name">${esc(habit.name)}</span> <button class="icon" data-action="habit-up" data-id="${habit.id}">↑</button><button class="icon" data-action="habit-down" data-id="${habit.id}">↓</button><button class="icon" data-action="habit-edit" data-id="${habit.id}">✎</button><button class="icon" data-action="habit-delete" data-id="${habit.id}">×</button></td>${dates.map(date => { const done = Boolean(week.completions[S.dateKey(date)]?.[habit.id]); return `<td><button class="circle ${done?'done':''}" data-action="weekly-toggle" data-id="${habit.id}" data-date="${S.dateKey(date)}">${done?'✓':''}</button></td>`; }).join('')}</tr>`).join('')}</tbody></table></div>`; }
  function renderDaily() { const key = S.dateKey(cursor), items = state.daily[key] || [], goals = state.dailyGoals?.[key] || [], done = items.filter(item => item.completed).length; const cards = items.length ? `<ul class="list daily-list">${items.map(item => `<li class="row daily-row ${item.completed?'done':''}" data-section="daily" data-date="${key}" data-id="${item.id}"><span class="drag" draggable="true" title="按住拖动排序">⠿</span><button class="circle ${item.completed?'done':''}" data-action="toggle" data-section="daily" data-date="${key}" data-id="${item.id}">${item.completed?'✓':''}</button><span class="daily-time">${esc(item.time || '—')}</span><span class="name">${esc(item.name)}</span><button class="icon" data-action="edit" data-section="daily" data-date="${key}" data-id="${item.id}">✎</button><button class="icon" data-action="up" data-section="daily" data-date="${key}" data-id="${item.id}">↑</button><button class="icon" data-action="down" data-section="daily" data-date="${key}" data-id="${item.id}">↓</button><button class="icon" data-action="delete" data-section="daily" data-date="${key}" data-id="${item.id}">×</button></li>`).join('')}</ul>` : '<div class="daily-empty"><strong>今天想完成什么？</strong><span>从一件小事开始也很好。</span><button data-action="add-daily">新增待办</button></div>'; const goalCards = goals.length ? goals.map(goal => `<section class="goal-card"><div class="goal-title"><strong>${esc(goal.name)}</strong><span>${goal.circles.filter(Boolean).length}/${goal.circles.length} 已完成</span></div><div class="goal-circles">${goal.circles.map((marked,index)=>`<div class="goal-unit"><button class="goal-circle ${marked?'done':''}" data-action="goal-toggle" data-goal="${goal.id}" data-index="${index}">${marked?'✓':''}</button><button class="goal-label" data-action="goal-label" data-goal="${goal.id}" data-index="${index}" title="点击修改文字">${esc(goal.labels[index] || `第${index+1}项`)}</button></div>`).join('')}</div></section>`).join('') : '<p class="goal-empty">比如新增“喝水”并设为 5 个圆圈；每个圆圈下方的小字都能单独修改。</p>'; return `<div class="content daily-page"><div class="daily-head"><div><p>今天的安排</p><h2>${dateLabel(cursor)}</h2><span>${done} / ${items.length} 已完成</span></div><div class="daily-nav"><button data-action="prev">← 前一天</button><button data-action="next">后一天 →</button><button data-action="add-daily">＋ 新增待办</button></div></div>${cards}<section class="daily-goals"><div class="goal-head"><div><p>每日待做</p><h3>小目标打卡</h3></div><button data-action="goal-add">＋ 新增小目标</button></div>${goalCards}</section><div class="daily-bottom"><button data-action="clear" data-clear="daily">清空当天待办</button></div></div>`; }
  function renderDailyGoals() { const key=S.dateKey(cursor), goals=state.dailyGoals?.[key]||[]; const cards=goals.length?goals.map(goal=>`<section class="goal-card"><div class="goal-title"><strong>${esc(goal.name)}</strong><span>${goal.circles.filter(Boolean).length}/${goal.circles.length} 已完成</span><div class="goal-actions"><button data-action="goal-add-circle" data-goal="${goal.id}">＋ 添加圆圈</button><button data-action="goal-remove-circle" data-goal="${goal.id}">－ 删除圆圈</button></div></div><div class="goal-circles">${goal.circles.map((marked,index)=>`<div class="goal-unit"><button class="goal-circle ${marked?'done':''}" data-action="goal-toggle" data-goal="${goal.id}" data-index="${index}">${marked?'✓':''}</button><button class="goal-label" data-action="goal-label" data-goal="${goal.id}" data-index="${index}" title="点击修改文字">${esc(goal.labels[index]||`第${index+1}次`)}</button></div>`).join('')}</div></section>`).join(''):'<p class="goal-empty">新增“喝水”等事项，设置圆圈数量；圆圈下方的小字可以单独改。</p>'; return `<div class="content daily-goals-page"><div class="daily-head"><div><p>每天重复的小事</p><h2>${dateLabel(cursor)} 每日待办</h2></div><div class="daily-nav"><button data-action="prev">← 前一天</button><button data-action="next">后一天 →</button><button data-action="goal-add">＋ 新增事项</button></div></div><section class="daily-goals"><div class="goal-head"><div><p>每日待办</p></div><button data-action="goal-add">＋ 新增事项</button></div>${cards}</section></div>`; }
  function shoppingGroup(group, title) { const items = state.shopping[group] || (state.shopping[group] = []); return `<section class="group"><h3>${title}</h3><div class="toolbar"><button data-action="add-shopping" data-group="${group}">新增${title}</button></div>${list(items, `data-section="shopping" data-group="${group}"`)}</section>`; }
  function renderShopping() { return `<div class="content">${toolbar('购物清单', '', '', 'shopping', true)}${shoppingGroup('ordinary','购物项目')}${shoppingGroup('consumables','消耗品')}</div>`; }
  async function recipeImage(recipe) { return recipe.imageId ? await RecipeImages.get(recipe.imageId) : null; }
  function renderRecipes() { return `<div class="content recipe-overview">${toolbar('菜品总览', '', '<button data-action="new-recipe">新建菜谱</button>', 'recipes', true)}<div class="recipe-wall">${state.recipes.length ? state.recipes.map(recipe => `<button class="recipe-tile" data-action="open-recipe" data-id="${recipe.id}"><img data-image="${recipe.id}" alt="${esc(recipe.name)}"><strong title="${esc(recipe.name)}">${esc(recipe.name).slice(0,7)}</strong></button>`).join('') : '<p class="empty">新建第一道菜吧。</p>'}</div></div>`; }
  function renderRecipe() { const recipe = state.recipes.find(item => item.id === selectedRecipeId) || state.recipes[0]; if (!recipe) return `<div class="content">${toolbar('菜谱', '', '<button data-action="new-recipe">新建菜谱</button>', 'recipes')}<p class="empty">还没有菜谱。点击“新建菜谱”开始。</p></div>`; selectedRecipeId = recipe.id; const index = state.recipes.indexOf(recipe); return `<div class="content">${toolbar(`菜谱 ${index+1}/${state.recipes.length}`, '', '<button data-action="new-recipe">新建菜谱</button><button data-action="delete-recipe">删除这道菜</button>', 'recipes')}<div class="recipe-form"><label>菜名<input id="recipe-name" value="${esc(recipe.name)}"></label><div><label class="button" for="recipe-image">添加 / 替换图片</label><input id="recipe-image" type="file" accept="image/*" hidden><p>图片会压缩后保存在浏览器本地。</p><img class="preview" id="recipe-preview" alt="菜品图片" hidden></div><label>详解<textarea id="recipe-notes" placeholder="在这里自由写做菜步骤、配料、提醒……">${esc(recipe.notes)}</textarea></label></div></div>`; }
  function monthGrid(interactive) { const year=cursor.getFullYear(), month=cursor.getMonth(), first=new Date(year,month,1), offset=(first.getDay()+6)%7, days=new Date(year,month+1,0).getDate(); return `<div class="month-grid">${['一','二','三','四','五','六','日'].map(day=>`<b>${day}</b>`).join('')}${Array.from({length:offset},()=>'<i></i>').join('')}${Array.from({length:days},(_,i)=>{const key=S.dateKey(new Date(year,month,i+1)), ids=state.monthly.marks[key]||[], selected=selectedMonthlyId&&ids.includes(selectedMonthlyId), colors=interactive ? (selected ? [state.monthly.items.find(x=>x.id===selectedMonthlyId)?.color] : []) : ids.map(id=>state.monthly.items.find(x=>x.id===id)).filter(item=>item && item.showInOverview !== false).map(item=>item.color), style=colors.length?`style="background:${colors.length===1?colors[0]:`conic-gradient(${colors.map((c,n)=>`${c} ${n/colors.length*100}% ${(n+1)/colors.length*100}%`).join(',')})`}"`:''; return `<button class="month-day ${selected?'marked':''}" data-action="monthly-toggle" data-day="${key}" ${interactive?'':'disabled'}><span>${i+1}</span><em ${style}></em></button>`;}).join('')}</div>`; }
  function monthTitle(){return `${cursor.getFullYear()}年${cursor.getMonth()+1}月`;}
  function renderMonthlyOverview(){return `<div class="content"><div class="daily-head"><div><p>一眼看整月</p><h2>${monthTitle()} 月度总览</h2></div><div class="daily-nav"><button data-action="month-prev">← 上个月</button><button data-action="month-next">下个月 →</button></div></div>${monthGrid(false)}</div>`;}
  function renderMonthlyItem(){const item=state.monthly.items.find(x=>x.id===selectedMonthlyId)||state.monthly.items[0]; if(item)selectedMonthlyId=item.id; return `<div class="content"><div class="daily-head"><div><p>选择一个事项来打卡</p><h2>${monthTitle()} 单项月历</h2></div><div class="daily-nav"><button data-action="month-prev">←</button><button data-action="month-next">→</button><button data-action="monthly-add">新增事项</button></div></div><div class="monthly-tools">${item?`<select id="monthly-select">${state.monthly.items.map(x=>`<option value="${x.id}" ${x.id===item.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><input id="monthly-color" type="color" value="${item.color}"><label><input id="monthly-show" type="checkbox" ${item.showInOverview !== false?'checked':''}> 在月度总览展示</label><button data-action="monthly-edit">改名</button><button data-action="monthly-delete">删除事项</button>`:'<button data-action="monthly-add">新增第一个事项</button>'}</div>${item?monthGrid(true):'<p class="empty">还没有事项，例如：拉屎、洗头发。</p>'}</div>`;}
  function renderLedger(){const month=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}`,rows=state.ledger.transactions.filter(x=>x.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="content"><div class="daily-head"><div><p>本月收支</p><h2>${month} 记账</h2></div><div class="daily-nav"><button data-action="month-prev">←</button><button data-action="month-next">→</button><button data-action="category-add">管理类别</button><button data-action="ledger-add">新增记录</button></div></div><div class="ledger-list">${rows.map(x=>{const c=state.ledger.categories.find(c=>c.id===x.categoryId);return `<div class="row"><i class="ledger-dot" style="background:${c?.color||'#b8aaa0'}"></i><span>${x.type==='income'?'+':'−'} ¥${S.formatMoney(x.amount)}</span><span class="name">${esc(c?.name||'未分类')} · ${esc(x.note||'未命名记录')}</span><button class="ledger-category" data-action="ledger-category" data-id="${x.id}">${esc(c?.name||'设置类别')}</button><small>${x.date}</small><button class="icon" title="编辑这条记录" data-action="ledger-edit" data-id="${x.id}">✎</button><button class="icon ledger-delete" title="删除这条记录" data-action="ledger-delete" data-id="${x.id}">×</button></div>`;}).join('')||'<p class="empty">本月还没有记录。</p>'}</div></div>`;}
  function renderLedgerOverview(){const month=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}`,s=S.ledgerSummary(state,month);return `<div class="content"><h2>${month} 总览</h2><div class="ledger-cards"><div>总收入<strong>¥${S.formatMoney(s.income)}</strong></div><div>总支出<strong>¥${S.formatMoney(s.expense)}</strong></div><div>结余<strong>¥${S.formatMoney(s.balance)}</strong></div></div></div>`;}
  function decorateDailyGoalPage() { view.querySelectorAll('.goal-unit').forEach(unit=>{const circle=unit.querySelector('.goal-circle'),remove=document.createElement('button');remove.className='goal-remove-one';remove.dataset.action='goal-remove-one';remove.dataset.goal=circle.dataset.goal;remove.dataset.index=circle.dataset.index;remove.title='删除这个圆圈';remove.textContent='×';unit.append(remove);}); const memo=document.createElement('section');memo.className='daily-memo';memo.innerHTML=`<label>备忘录<textarea id="daily-fixed-memo" placeholder="写下需要长期记住的事……">${esc(state.fixedDailyMemo||'')}</textarea></label><small>固定备忘录，不随日期变化</small>`;view.querySelector('.daily-goals')?.append(memo); }
  function decorateDailyPlan() { const day=S.dateKey(cursor),memo=document.createElement('section');memo.className='daily-memo';memo.innerHTML=`<label>备忘录<textarea id="daily-memo" placeholder="写下今天需要记住的事……">${esc(state.dailyMemos?.[day]||'')}</textarea></label><small>自动按当天保存</small>`;view.querySelector('.daily-bottom')?.before(memo); view.querySelectorAll('.daily-row').forEach(row=>{const task=state.daily[day]?.find(item=>item.id===row.dataset.id),star=document.createElement('button');row.classList.toggle('starred',Boolean(task?.starred));star.className=`daily-star ${task?.starred?'starred':''}`;star.dataset.action='daily-star';star.dataset.id=row.dataset.id;star.dataset.date=day;star.title='星标待办';star.textContent=task?.starred?'★':'☆';row.querySelector('.daily-time')?.before(star);}); }
  function decorateDateJump() { if(!['weekly','daily','daily-goals','daily-review','ledger','monthly-overview','monthly-item'].includes(tab))return;const target=view.querySelector('.daily-nav, .toolbar');if(!target)return;const button=document.createElement('button');button.dataset.action='today';button.textContent='今天';button.title='跳转到当前日期';target.append(button); }
  function renderDailyReview(){const day=S.dateKey(cursor);return `<div class="content daily-review"><div class="daily-head"><div><p>留给自己的片刻</p><h2>${dateLabel(cursor)} 每日复盘</h2></div><div class="daily-nav"><input id="review-date" type="date" value="${day}" title="跳转到指定日期"><button data-action="review-prev">← 前一天</button><button data-action="review-next">后一天 →</button></div></div><section class="review-card"><label>备忘录<textarea id="daily-review" placeholder="今天发生了什么？有什么想记下来的？">${esc(state.dailyReviews?.[day]||'')}</textarea></label><small>自动按当天保存</small></section></div>`;}
  function render() { document.querySelectorAll('[data-tab]').forEach(button => button.classList.toggle('active', button.dataset.tab === tab)); if (tab === 'daily-goals') syncDailyGoalView(S.dateKey(cursor)); view.innerHTML = tab === 'weekly' ? renderWeekly() : tab === 'daily' ? renderDaily() : tab === 'daily-review' ? renderDailyReview() : tab === 'daily-goals' ? renderDailyGoals() : tab === 'shopping' ? renderShopping() : tab === 'ledger' ? renderLedger() : tab === 'ledger-overview' ? renderLedgerOverview() : tab === 'monthly-overview' ? renderMonthlyOverview() : tab === 'monthly-item' ? renderMonthlyItem() : tab === 'recipes' ? renderRecipes() : renderRecipe(); if (tab === 'daily') decorateDailyPlan(); if (tab === 'daily-goals') decorateDailyGoalPage(); decorateDateJump(); if (tab === 'recipes') loadThumbs(); if (tab === 'recipe') loadPreview(); }
  async function loadThumbs() { for (const image of view.querySelectorAll('[data-image]')) { const source = await RecipeImages.get(image.dataset.image); if (source) image.src = source; } }
  async function loadPreview() { const recipe = state.recipes.find(item => item.id === selectedRecipeId); const source = recipe && await recipeImage(recipe); const image = document.querySelector('#recipe-preview'); if (source) { image.src = source; image.hidden = false; } }
  function saveRecipeField() { const recipe = state.recipes.find(item => item.id === selectedRecipeId); if (!recipe) return; try { S.updateRecipe(state, recipe.id, { name: document.querySelector('#recipe-name').value, notes: document.querySelector('#recipe-notes').value }); save(); show('菜谱已保存'); } catch (error) { show(error.message); render(); } }
  view.addEventListener('change', async event => { if (event.target.id === 'recipe-image') { const recipe = state.recipes.find(item => item.id === selectedRecipeId); try { await RecipeImages.put(recipe.id, event.target.files[0]); S.updateRecipe(state,recipe.id,{imageId:recipe.id}); save(); loadPreview(); show('图片已保存'); } catch(error) { show(error.message); } } });
  view.addEventListener('blur', event => { if (event.target.id === 'recipe-name' || event.target.id === 'recipe-notes') saveRecipeField(); }, true);
  let dragged = null;
  view.addEventListener('dragstart', event => { const row = event.target.closest('[data-weekly-id], .row[data-id]'); if (!row) return; dragged = row; event.dataTransfer.effectAllowed = 'move'; });
  view.addEventListener('dragover', event => { if (dragged && event.target.closest('[data-weekly-id], .row[data-id]')) event.preventDefault(); });
  view.addEventListener('drop', event => { const target = event.target.closest('[data-weekly-id], .row[data-id]'); if (!dragged || !target || dragged === target) return; event.preventDefault(); try { if (dragged.dataset.weeklyId && target.dataset.weeklyId) { const from = state.weekly.habits.findIndex(item => item.id === dragged.dataset.weeklyId), to = state.weekly.habits.findIndex(item => item.id === target.dataset.weeklyId); S.moveHabit(state, dragged.dataset.weeklyId, to > from ? to - from : to - from); } else if (dragged.dataset.section === target.dataset.section && dragged.dataset.group === target.dataset.group && dragged.dataset.date === target.dataset.date) { const list = target.dataset.section === 'daily' ? state.daily[target.dataset.date] : state.shopping[target.dataset.group]; const from = list.findIndex(item => item.id === dragged.dataset.id), to = list.findIndex(item => item.id === target.dataset.id), delta = to > from ? to - from : to - from; target.dataset.section === 'daily' ? S.moveListItem(state,'daily',target.dataset.date,dragged.dataset.id,delta) : S.moveShoppingItem(state,target.dataset.group,dragged.dataset.id,delta); } save(); render(); } finally { dragged = null; } });
  view.addEventListener('dragend', () => { dragged = null; });
  view.addEventListener('click', event => { const button = event.target.closest('[data-action="add-daily"]'); if (!button) return; event.stopImmediatePropagation(); const name = prompt('待办名称'); if (name === null) return; const time = prompt('时间（可不填，例如 09:00）'); try { S.addListItem(state, 'daily', S.dateKey(cursor), name, id, time || ''); save(); render(); } catch (error) { show(error.message); } });
  view.addEventListener('click', event => { const button = event.target.closest('[data-action="goal-add"], [data-action="goal-toggle"], [data-action="goal-label"], [data-action="goal-add-circle"], [data-action="goal-remove-circle"]'); if (!button) return; event.stopImmediatePropagation(); const day = S.dateKey(cursor); try { if (button.dataset.action === 'goal-add') { const name = prompt('每日待办名称（例如：喝水）'); if (name === null) return; const countText = prompt('需要几个圆圈？', '5'); if (countText === null) return; const count = Number.parseInt(countText, 10); if (!Number.isInteger(count) || count < 1 || count > 12) throw new Error('圆圈数量请输入 1 到 12'); S.addDailyGoal(state, day, name, Array.from({ length: count }, (_, index) => `第${index + 1}次`), id); } else if (button.dataset.action === 'goal-toggle') { S.toggleDailyGoalCircle(state, day, button.dataset.goal, Number(button.dataset.index)); } else if (button.dataset.action === 'goal-add-circle') { const goal=state.dailyGoals?.[day]?.find(item=>item.id===button.dataset.goal); S.addDailyGoalCircle(state,day,button.dataset.goal,`第${(goal?.labels.length||0)+1}次`); } else if (button.dataset.action === 'goal-remove-circle') { S.removeDailyGoalCircle(state,day,button.dataset.goal); } else { const goal = state.dailyGoals?.[day]?.find(item => item.id === button.dataset.goal); const value = prompt('圆圈下方的小字', goal?.labels[Number(button.dataset.index)] || ''); if (value === null) return; S.renameDailyGoalCircle(state, day, button.dataset.goal, Number(button.dataset.index), value); } save(); render(); } catch (error) { show(error.message); } });
  view.addEventListener('click', event => { if (tab !== 'daily-goals') return; const button = event.target.closest('[data-action="prev"], [data-action="next"]'); if (!button) return; event.stopImmediatePropagation(); cursor.setDate(cursor.getDate() + (button.dataset.action === 'prev' ? -1 : 1)); render(); });
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="review-prev"], [data-action="review-next"]');if(!button)return;event.stopImmediatePropagation();cursor.setDate(cursor.getDate()+(button.dataset.action==='review-prev'?-1:1));render();});
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="today"]');if(!button)return;event.stopImmediatePropagation();cursor=new Date();render();});
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="daily-star"]');if(!button)return;event.stopImmediatePropagation();try{S.toggleListStar(state,'daily',button.dataset.date,button.dataset.id);save();render();}catch(error){show(error.message);}});
  view.addEventListener('change', event => { if(event.target.id!=='review-date')return;cursor=new Date(`${event.target.value}T00:00:00`);render();});
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="goal-remove-one"]'); if(!button)return; event.stopImmediatePropagation(); try{S.removeDailyGoalCircle(state,S.dateKey(cursor),button.dataset.goal,Number(button.dataset.index));save();render();}catch(error){show(error.message);}});
  view.addEventListener('blur', event => { if(event.target.id==='daily-memo'){S.setDailyMemo(state,S.dateKey(cursor),event.target.value);save();show('当天备忘录已保存');} if(event.target.id==='daily-fixed-memo'){S.setFixedDailyMemo(state,event.target.value);save();show('固定备忘录已保存');} if(event.target.id==='daily-review'){S.setDailyReview(state,S.dateKey(cursor),event.target.value);save();show('每日复盘已保存');}},true);
  view.addEventListener('click', event => { const button=event.target.closest('[data-action^="monthly"], [data-action="month-prev"], [data-action="month-next"]'); if(!button)return; event.stopImmediatePropagation(); try { const a=button.dataset.action; if(a==='month-prev')cursor.setMonth(cursor.getMonth()-1); if(a==='month-next')cursor.setMonth(cursor.getMonth()+1); if(a==='monthly-add'){const name=prompt('事项名称');if(name===null)return;const color=prompt('颜色（例如 #f6ce52）','#f6ce52');if(color===null)return;S.addMonthlyItem(state,name,color,id);selectedMonthlyId=state.monthly.items.at(-1).id;} if(a==='monthly-edit'){const item=state.monthly.items.find(x=>x.id===selectedMonthlyId);const name=prompt('事项名称',item.name);if(name!==null)S.updateMonthlyItem(state,item.id,{name});} if(a==='monthly-delete'&&confirm('删除这个事项及其所有标记吗？')){S.deleteMonthlyItem(state,selectedMonthlyId);selectedMonthlyId=state.monthly.items[0]?.id||null;} if(a==='monthly-toggle')S.toggleMonthlyMark(state,selectedMonthlyId,button.dataset.day);save();render();}catch(error){show(error.message);} });
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="ledger-add"], [data-action="category-add"]'); if(!button)return; event.stopImmediatePropagation(); try { if(button.dataset.action==='category-add'){const name=prompt('类别名称');if(name===null)return;const color=prompt('类别颜色（例如 #c96f4c）','#c96f4c');if(color===null)return;S.addCategory(state,name,color,id);} else {const type=prompt('输入 income 为收入，expense 为支出','expense');if(type===null)return;const amount=prompt('金额');if(amount===null)return;const note=prompt('备注（可不填）','')||'';const names=state.ledger.categories.map(c=>c.name).join('、');const chosen=prompt(`类别名称（已有：${names||'暂无'}）`,'')||'';const category=state.ledger.categories.find(c=>c.name===chosen);S.addTransaction(state,{type,amount,date:S.dateKey(new Date()),categoryId:category?.id||null,note},id);} save();render(); } catch(error){show(error.message);} });
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="ledger-category"]'); if(!button)return; event.stopImmediatePropagation(); try{const names=state.ledger.categories.map(item=>item.name).join('、');const name=prompt(`类别名称（已有：${names||'暂无；输入名称会自动新建'}）`,'');if(name===null)return;const text=name.trim();if(!text){S.setTransactionCategory(state,button.dataset.id,null);}else{let category=state.ledger.categories.find(item=>item.name===text);if(!category){S.addCategory(state,text,'#b8aaa0',id);category=state.ledger.categories.at(-1);}S.setTransactionCategory(state,button.dataset.id,category.id);}save();render();}catch(error){show(error.message);}});
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="ledger-edit"]'); if(!button)return; event.stopImmediatePropagation(); try{const entry=state.ledger.transactions.find(item=>item.id===button.dataset.id);const type=prompt('收入填 income，支出填 expense',entry.type);if(type===null)return;const amount=prompt('金额',String(entry.amount));if(amount===null)return;const note=prompt('备注（可不填）',entry.note);if(note===null)return;S.updateTransaction(state,entry.id,{type,amount,note});save();render();}catch(error){show(error.message);}});
  view.addEventListener('click', event => { const button=event.target.closest('[data-action="ledger-delete"]'); if(!button)return; event.stopImmediatePropagation(); if(!confirm('删除这条记账记录吗？'))return; try{S.deleteTransaction(state,button.dataset.id);save();render();}catch(error){show(error.message);}});
  view.addEventListener('change', event => { if(event.target.id==='monthly-select'){selectedMonthlyId=event.target.value;render();} if(event.target.id==='monthly-color'){try{S.updateMonthlyItem(state,selectedMonthlyId,{color:event.target.value});save();render();}catch(error){show(error.message);}} if(event.target.id==='monthly-show'){try{S.updateMonthlyItem(state,selectedMonthlyId,{showInOverview:event.target.checked});save();render();}catch(error){show(error.message);}} });
  view.addEventListener('click', async event => { const button = event.target.closest('button'); if (!button) return; const a = button.dataset.action, itemId = button.dataset.id, group = button.dataset.group, section = button.dataset.section, date = button.dataset.date; try { if (a === 'prev') { if (tab === 'weekly') cursor.setDate(cursor.getDate()-7); else if (tab === 'daily') cursor.setDate(cursor.getDate()-1); else if (tab === 'recipe') { const i = state.recipes.findIndex(r=>r.id===selectedRecipeId); if(i>0) selectedRecipeId=state.recipes[i-1].id; } render(); return; } if (a === 'next') { if (tab === 'weekly') cursor.setDate(cursor.getDate()+7); else if (tab === 'daily') cursor.setDate(cursor.getDate()+1); else if (tab === 'recipe') { const i=state.recipes.findIndex(r=>r.id===selectedRecipeId); if(i<state.recipes.length-1) selectedRecipeId=state.recipes[i+1].id; } render(); return; } if (a === 'clear') { if(confirm('确定清空当前页面的数据吗？此操作不能恢复。')) { if (button.dataset.clear === 'recipes') await Promise.all(state.recipes.map(recipe => RecipeImages.remove(recipe.id))); S.clearSection(state,button.dataset.clear,button.dataset.clear==='daily'?S.dateKey(cursor):null); save(); render(); } return; } if (a === 'weekly-toggle') S.toggleCompletion(state,itemId,new Date(`${date}T00:00:00`)); if (a === 'habit-up') S.moveHabit(state,itemId,-1); if (a === 'habit-down') S.moveHabit(state,itemId,1); if (a === 'habit-edit') S.renameHabit(state,itemId,prompt('习惯名称') || ''); if (a === 'habit-delete' && confirm('删除这个习惯吗？')) S.deleteHabit(state,itemId); if (a === 'add-habit') S.addHabit(state,prompt('习惯名称') || '',id); if (a === 'add-shopping') S.addShoppingItem(state,group,prompt(group === 'consumables' ? '消耗品名称' : '购物项目名称') || '',id); if (a === 'toggle') section==='daily' ? S.toggleListItem(state,'daily',date,itemId) : S.toggleShoppingItem(state,group,itemId); if (a === 'up') section==='daily' ? S.moveListItem(state,'daily',date,itemId,-1) : S.moveShoppingItem(state,group,itemId,-1); if (a === 'down') section==='daily' ? S.moveListItem(state,'daily',date,itemId,1) : S.moveShoppingItem(state,group,itemId,1); if (a === 'edit') { const value=prompt('修改名称'); if(value!==null) section==='daily'?S.renameListItem(state,'daily',date,itemId,value):S.renameShoppingItem(state,group,itemId,value); } if (a === 'delete' && confirm('删除这一项吗？')) section==='daily'?S.deleteListItem(state,'daily',date,itemId):S.deleteShoppingItem(state,group,itemId); if (a === 'new-recipe') { S.addRecipe(state,prompt('菜名') || '',id); selectedRecipeId=state.recipes.at(-1).id; tab='recipe'; } if (a === 'open-recipe') { selectedRecipeId=itemId; tab='recipe'; } if (a === 'delete-recipe' && confirm('删除这道菜及其图片吗？')) { await RecipeImages.remove(selectedRecipeId); S.deleteRecipe(state,selectedRecipeId); selectedRecipeId=state.recipes[0]?.id || null; } save(); render(); } catch(error) { show(error.message); } });
  let draggedTab = null, ignoreTabClickUntil = 0;
  nav.addEventListener('dragstart', event => { const handle = event.target.closest('.nav-drag'); if (!handle) return; const button = handle.closest('[data-tab]'); draggedTab = button; handle.classList.add('tab-dragging'); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', button.dataset.tab); });
  nav.addEventListener('dragover', event => { const target = event.target.closest('[data-tab]'); if (!draggedTab || !target || target === draggedTab) return; event.preventDefault(); const box = target.getBoundingClientRect(); nav.insertBefore(draggedTab, event.clientX < box.left + box.width / 2 ? target : target.nextSibling); });
  nav.addEventListener('drop', event => { if (!draggedTab) return; event.preventDefault(); saveNavOrder(); ignoreTabClickUntil = Date.now() + 250; });
  nav.addEventListener('dragend', () => { if (draggedTab) { draggedTab.querySelector('.nav-drag')?.classList.remove('tab-dragging'); saveNavOrder(); ignoreTabClickUntil = Date.now() + 250; } draggedTab = null; });
  nav.addEventListener('click', event => { if (Date.now() < ignoreTabClickUntil) return; const button=event.target.closest('[data-tab]'); if(button) changeTab(button.dataset.tab); });
  document.querySelector('#export').addEventListener('click', async () => { try { const backup={version:1,state,images:await RecipeImages.exportAll()}; const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url; a.download=`我的计划本备份_${S.dateKey(new Date())}.json`; a.click(); URL.revokeObjectURL(url); show('已开始下载备份；请在浏览器弹窗中选择 D:\\我的计划本。'); } catch(error) { show(error.message); } });
  document.querySelector('#restore').addEventListener('change', async event => { const file=event.target.files[0]; if(!file) return; const previousState=state, previousImages=await RecipeImages.exportAll(); try { const backup=JSON.parse(await file.text()); if(!backup || !S.validV3(backup.state) || !RecipeImages.validateBackupImages(backup.images)) throw new Error('这不是可用的计划本备份'); if(!confirm('恢复会覆盖当前本地数据，确定继续吗？')) return; await RecipeImages.restore(backup.images); state=backup.state; selectedRecipeId=state.recipes[0]?.id||null; S.save(localStorage,state); render(); show('备份已恢复'); } catch(error) { state=previousState; try { await RecipeImages.restore(previousImages); S.save(localStorage,previousState); } catch (_) {} show(error.message); } finally { event.target.value=''; } });
  restoreNavOrder();
  render();
})();
