(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.HabitStore = api;
})(globalThis, function () {
  const STORAGE_KEY = 'weekly-habit-tracker:v1';
  const DEFAULT_HABITS = ['早起', '喝水', '运动', '阅读'];
  const GROUPS = ['ordinary', 'consumables'];
  const createWeekly = () => ({ habits: DEFAULT_HABITS.map((name, index) => ({ id: `habit-${index + 1}`, name })), completions: {} });
  const createInitialState = () => ({ version: 5, weekly: createWeekly(), daily: {}, dailyGoals: {}, dailyGoalTemplates: [], dailyGoalChecks: {}, dailyMemos: {}, dailyReviews: {}, fixedDailyMemo: '', shopping: { ordinary: [], consumables: [] }, recipes: [], monthly: { items: [], marks: {} }, ledger: { categories: [], transactions: [] } });
  const localDate = value => new Date(value.getFullYear(), value.getMonth(), value.getDate());
  function weekStart(value) { const date = localDate(value); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; }
  function weekDates(value) { const start = weekStart(value); return Array.from({ length: 7 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; }); }
  const dateKey = value => { const date = localDate(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };
  const validId = value => typeof value === 'string' && value.trim().length > 0;
  const validName = value => typeof value === 'string' && value.trim().length > 0;
  const validItem = value => value && validId(value.id) && validName(value.name) && typeof value.completed === 'boolean' && (value.time === undefined || typeof value.time === 'string');
  const validList = value => Array.isArray(value) && value.every(validItem);
  const validWeekly = value => value && Array.isArray(value.habits) && value.habits.every(item => item && validId(item.id) && validName(item.name)) && value.completions && typeof value.completions === 'object' && Object.values(value.completions).every(day => day && typeof day === 'object' && !Array.isArray(day) && Object.values(day).every(flag => flag === true));
  const validDaily = value => value && typeof value === 'object' && !Array.isArray(value) && Object.values(value).every(validList);
  const validRecipe = value => value && validId(value.id) && validName(value.name) && typeof value.notes === 'string' && (value.imageId === null || validId(value.imageId));
  const validMonthly = value => value && Array.isArray(value.items) && value.items.every(item => item && validId(item.id) && validName(item.name) && /^#[0-9a-f]{6}$/i.test(item.color)) && value.marks && typeof value.marks === 'object' && Object.values(value.marks).every(ids => Array.isArray(ids) && ids.every(validId));
  const validV3 = state => state && state.version === 3 && validWeekly(state.weekly) && validDaily(state.daily) && state.shopping && validList(state.shopping.ordinary) && validList(state.shopping.consumables) && Array.isArray(state.recipes) && state.recipes.every(validRecipe);
  const validV4 = state => state && state.version === 4 && validV3({ ...state, version: 3 }) && validMonthly(state.monthly);
  const validV5 = state => state && state.version === 5 && validV4({ ...state, version: 4 }) && state.ledger && Array.isArray(state.ledger.categories) && Array.isArray(state.ledger.transactions);
  const validV2 = state => state && state.version === 2 && validWeekly(state.weekly) && validDaily(state.daily) && validList(state.shopping);
  const validV1 = state => state && state.version === 1 && validWeekly(state);
  function load(storage) { try { const saved = JSON.parse(storage.getItem(STORAGE_KEY) || 'null'); if (validV5(saved)) return saved; if (validV4(saved)) return { ...saved, version: 5, ledger: { categories: [], transactions: [] } }; if (validV3(saved)) return { ...saved, version: 5, monthly: { items: [], marks: {} }, ledger: { categories: [], transactions: [] } }; if (validV2(saved)) return { version: 5, weekly: saved.weekly, daily: saved.daily, shopping: { ordinary: saved.shopping, consumables: [] }, recipes: [], monthly: { items: [], marks: {} }, ledger: { categories: [], transactions: [] } }; if (validV1(saved)) return { version: 5, weekly: { habits: saved.habits, completions: saved.completions }, daily: {}, shopping: { ordinary: [], consumables: [] }, recipes: [], monthly: { items: [], marks: {} }, ledger: { categories: [], transactions: [] } }; } catch (_) {} return createInitialState(); }
  function save(storage, state) { if (!validV5(state)) throw new Error('计划数据格式不正确，未保存'); storage.setItem(STORAGE_KEY, JSON.stringify(state)); }
  function clear(storage) { storage.removeItem(STORAGE_KEY); }
  const weeklyOf = state => state.weekly || state;
  function validateHabitName(value, habits) { const name = String(value || '').trim(); if (!name) return '请输入习惯名称'; if (habits.some(item => item.name === name)) return '这个习惯已经存在'; return ''; }
  function addHabit(state, value, makeId) { const weekly = weeklyOf(state); const error = validateHabitName(value, weekly.habits); if (error) throw new Error(error); weekly.habits.push({ id: makeId(), name: String(value).trim() }); }
  function renameHabit(state, id, value) { const weekly = weeklyOf(state); const habit = weekly.habits.find(item => item.id === id); const error = validateHabitName(value, weekly.habits.filter(item => item.id !== id)); if (!habit) throw new Error('没有找到这个习惯'); if (error) throw new Error(error); habit.name = String(value).trim(); }
  function deleteHabit(state, id) { const weekly = weeklyOf(state); weekly.habits = weekly.habits.filter(item => item.id !== id); Object.keys(weekly.completions).forEach(day => { delete weekly.completions[day][id]; if (!Object.keys(weekly.completions[day]).length) delete weekly.completions[day]; }); }
  function moveIn(list, id, delta) { const index = list.findIndex(item => item.id === id); const target = index + delta; if (index < 0 || target < 0 || target >= list.length) return; const [item] = list.splice(index, 1); list.splice(target, 0, item); }
  function moveHabit(state, id, delta) { moveIn(weeklyOf(state).habits, id, delta); }
  function toggleCompletion(state, id, date) { const weekly = weeklyOf(state); const day = dateKey(date); if (!weekly.habits.some(item => item.id === id)) throw new Error('没有找到这个习惯'); weekly.completions[day] ||= {}; if (weekly.completions[day][id]) delete weekly.completions[day][id]; else weekly.completions[day][id] = true; if (!Object.keys(weekly.completions[day]).length) delete weekly.completions[day]; }
  function groupList(state, group) { if (!GROUPS.includes(group)) throw new Error('未知购物分组'); return state.shopping[group]; }
  function listFor(state, section, date) { if (section === 'daily') return state.daily[date] || (state.daily[date] = []); throw new Error('未知清单类型'); }
  function validateItemName(value, items) { const name = String(value || '').trim(); if (!name) return '请输入名称'; if (items.some(item => item.name === name)) return '这个名称已经存在'; return ''; }
  function addTo(list, value, makeId, time = '') { const error = validateItemName(value, list); if (error) throw new Error(error); const item={ id: makeId(), name: String(value).trim(), completed: false, starred: false, time: String(time || '') },firstDone=list.findIndex(entry=>entry.completed); list.splice(firstDone<0?list.length:firstDone,0,item); }
  function renameIn(list, id, value) { const item = list.find(entry => entry.id === id); if (!item) throw new Error('没有找到这一项'); const error = validateItemName(value, list.filter(entry => entry.id !== id)); if (error) throw new Error(error); item.name = String(value).trim(); }
  function toggleIn(list, id) { const index = list.findIndex(entry => entry.id === id); if (index < 0) throw new Error('没有找到这一项'); const item = list[index]; item.completed = !item.completed; list.splice(index, 1); if (item.completed) list.push(item); else { const firstDone = list.findIndex(entry => entry.completed); list.splice(firstDone < 0 ? list.length : firstDone, 0, item); } }
  function deleteIn(list, id) { const index = list.findIndex(item => item.id === id); if (index >= 0) list.splice(index, 1); }
  function sortDaily(list){list.sort((a,b)=>Number(Boolean(b.starred))-Number(Boolean(a.starred))||Number(Boolean(a.completed))-Number(Boolean(b.completed))||(a.time||'99:99').localeCompare(b.time||'99:99'));}
  function addListItem(state, section, date, value, makeId, time = '') { const list = listFor(state, section, date); addTo(list, value, makeId, time); if (section === 'daily') sortDaily(list); }
  function renameListItem(state, section, date, id, value) { renameIn(listFor(state, section, date), id, value); }
  function toggleListItem(state, section, date, id) { const list=listFor(state,section,date);toggleIn(list,id);if(section==='daily')sortDaily(list); }
  function toggleListStar(state,section,date,id){const list=listFor(state,section,date),item=list.find(entry=>entry.id===id);if(!item)throw new Error('没有找到这一项');item.starred=!item.starred;if(section==='daily')sortDaily(list);}
  function deleteListItem(state, section, date, id) { deleteIn(listFor(state, section, date), id); }
  function moveListItem(state, section, date, id, delta) { moveIn(listFor(state, section, date), id, delta); }
  function addShoppingItem(state, group, value, makeId) { addTo(groupList(state, group), value, makeId); }
  function renameShoppingItem(state, group, id, value) { renameIn(groupList(state, group), id, value); }
  function toggleShoppingItem(state, group, id) { toggleIn(groupList(state, group), id); }
  function deleteShoppingItem(state, group, id) { deleteIn(groupList(state, group), id); }
  function moveShoppingItem(state, group, id, delta) { moveIn(groupList(state, group), id, delta); }
  function addRecipe(state, value, makeId) { const error = validateItemName(value, state.recipes); if (error) throw new Error(error); state.recipes.push({ id: makeId(), name: String(value).trim(), notes: '', imageId: null }); }
  function updateRecipe(state, id, changes) { const recipe = state.recipes.find(item => item.id === id); if (!recipe) throw new Error('没有找到这道菜'); if ('name' in changes) { const error = validateItemName(changes.name, state.recipes.filter(item => item.id !== id)); if (error) throw new Error(error); recipe.name = String(changes.name).trim(); } if ('notes' in changes) recipe.notes = String(changes.notes || ''); if ('imageId' in changes) recipe.imageId = changes.imageId || null; }
  function deleteRecipe(state, id) { deleteIn(state.recipes, id); }
  function moveRecipe(state, id, delta) { moveIn(state.recipes, id, delta); }
  function addMonthlyItem(state, name, color, makeId) { const error = validateItemName(name, state.monthly.items); if (error) throw new Error(error); if (!/^#[0-9a-f]{6}$/i.test(color)) throw new Error('请选择有效颜色'); state.monthly.items.push({ id: makeId(), name: String(name).trim(), color, showInOverview: false }); }
  function updateMonthlyItem(state, id, changes) { const item = state.monthly.items.find(entry => entry.id === id); if (!item) throw new Error('没有找到这个事项'); if ('name' in changes) { const error = validateItemName(changes.name, state.monthly.items.filter(entry => entry.id !== id)); if (error) throw new Error(error); item.name = String(changes.name).trim(); } if ('color' in changes) { if (!/^#[0-9a-f]{6}$/i.test(changes.color)) throw new Error('请选择有效颜色'); item.color = changes.color; } if ('showInOverview' in changes) item.showInOverview = Boolean(changes.showInOverview); }
  function deleteMonthlyItem(state, id) { state.monthly.items = state.monthly.items.filter(item => item.id !== id); Object.keys(state.monthly.marks).forEach(day => { state.monthly.marks[day] = state.monthly.marks[day].filter(mark => mark !== id); if (!state.monthly.marks[day].length) delete state.monthly.marks[day]; }); }
  function toggleMonthlyMark(state, id, day) { if (!state.monthly.items.some(item => item.id === id)) throw new Error('没有找到这个事项'); const marks = state.monthly.marks[day] || (state.monthly.marks[day] = []); const index = marks.indexOf(id); if (index >= 0) marks.splice(index, 1); else marks.push(id); if (!marks.length) delete state.monthly.marks[day]; }
  function addCategory(state, name, color, makeId) { const error=validateItemName(name,state.ledger.categories); if(error)throw new Error(error); state.ledger.categories.push({id:makeId(),name:String(name).trim(),color}); }
  function deleteCategory(state,id){state.ledger.categories=state.ledger.categories.filter(x=>x.id!==id);state.ledger.transactions.forEach(x=>{if(x.categoryId===id)x.categoryId=null;});}
  function addTransaction(state, entry, makeId){if(!['income','expense'].includes(entry.type)||!Number.isFinite(Number(entry.amount))||Number(entry.amount)<=0)throw new Error('金额必须大于 0');state.ledger.transactions.push({id:makeId(),type:entry.type,amount:Number(entry.amount),date:entry.date,categoryId:entry.categoryId||null,note:String(entry.note||'')});}
  function deleteTransaction(state,id){const index=state.ledger.transactions.findIndex(item=>item.id===id);if(index<0)throw new Error('没有找到这条记录');state.ledger.transactions.splice(index,1);}
  function setTransactionCategory(state,id,categoryId){const transaction=state.ledger.transactions.find(item=>item.id===id);if(!transaction)throw new Error('没有找到这条记录');if(categoryId!==null&&!state.ledger.categories.some(item=>item.id===categoryId))throw new Error('没有找到这个类别');transaction.categoryId=categoryId;}
  function updateTransaction(state,id,changes){const transaction=state.ledger.transactions.find(item=>item.id===id);if(!transaction)throw new Error('没有找到这条记录');const type=changes.type??transaction.type,amount=changes.amount??transaction.amount;if(!['income','expense'].includes(type)||!Number.isFinite(Number(amount))||Number(amount)<=0)throw new Error('金额必须大于 0');transaction.type=type;transaction.amount=Number(amount);if('note' in changes)transaction.note=String(changes.note||'');}
  function ledgerSummary(state,month){const rows=state.ledger.transactions.filter(x=>x.date.startsWith(month));const income=rows.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense=rows.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);return {income,expense,balance:income-expense};}
  function formatMoney(value){return Number(value).toFixed(2);}
  function ensureDailyGoals(state){state.dailyGoalTemplates ||= [];state.dailyGoalChecks ||= {};}
  function goalOf(state,id){ensureDailyGoals(state);const goal=state.dailyGoalTemplates.find(x=>x.id===id);if(!goal)throw new Error('没有找到每日待办');return goal;}
  function checksOf(state,day,goal){ensureDailyGoals(state);const checks=state.dailyGoalChecks[day]||(state.dailyGoalChecks[day]={});return checks[goal.id]||(checks[goal.id]=goal.labels.map(()=>false));}
  function addDailyGoal(state,day,name,labels,makeId){ensureDailyGoals(state);const text=String(name||'').trim();if(!text)throw new Error('请输入每日待办名称');if(state.dailyGoalTemplates.some(x=>x.name===text))throw new Error('这个每日待办已经存在');const goal={id:makeId(),name:text,labels:labels.map(String)};state.dailyGoalTemplates.push(goal);checksOf(state,day,goal);}
  function toggleDailyGoalCircle(state,day,id,index){const goal=goalOf(state,id),checks=checksOf(state,day,goal);checks[index]=!checks[index];}
  function renameDailyGoalCircle(state,day,id,index,label){const goal=goalOf(state,id);const text=String(label||'').trim();if(!text)throw new Error('请输入圆圈说明');goal.labels[index]=text;}
  function addDailyGoalCircle(state,day,id,label){const goal=goalOf(state,id);goal.labels.push(String(label||`第${goal.labels.length+1}次`).trim());Object.values(state.dailyGoalChecks).forEach(checks=>{if(checks[goal.id])checks[goal.id].push(false);});checksOf(state,day,goal);}
  function removeDailyGoalCircle(state,day,id,index){const goal=goalOf(state,id);if(goal.labels.length<=1)throw new Error('至少保留一个圆圈');const target=Number.isInteger(index)?index:goal.labels.length-1;goal.labels.splice(target,1);Object.values(state.dailyGoalChecks).forEach(checks=>{if(checks[goal.id])checks[goal.id].splice(target,1);});}
  function setDailyMemo(state,day,text){state.dailyMemos ||= {};const value=String(text||'');if(value)state.dailyMemos[day]=value;else delete state.dailyMemos[day];}
  function setFixedDailyMemo(state,text){state.fixedDailyMemo=String(text||'');}
  function setDailyReview(state,day,text){state.dailyReviews ||= {};const value=String(text||'');if(value)state.dailyReviews[day]=value;else delete state.dailyReviews[day];}
  function clearSection(state, section, date) { if (section === 'weekly') { state.weekly = createWeekly(); return; } if (section === 'daily') { delete state.daily[date]; if(state.dailyGoalChecks)delete state.dailyGoalChecks[date]; if(state.dailyMemos)delete state.dailyMemos[date]; return; } if (section === 'shopping') { state.shopping = { ordinary: [], consumables: [] }; return; } if (section === 'recipes') { state.recipes = []; return; } throw new Error('未知页面'); }
  return { STORAGE_KEY, createInitialState, load, save, clear, validV3: validV5, weekStart, weekDates, dateKey, validateHabitName, addHabit, renameHabit, deleteHabit, moveHabit, toggleCompletion, addListItem, renameListItem, toggleListItem, toggleListStar, deleteListItem, moveListItem, addShoppingItem, renameShoppingItem, toggleShoppingItem, deleteShoppingItem, moveShoppingItem, addRecipe, updateRecipe, deleteRecipe, moveRecipe, addMonthlyItem, updateMonthlyItem, deleteMonthlyItem, toggleMonthlyMark, addCategory, deleteCategory, addTransaction, deleteTransaction, setTransactionCategory, updateTransaction, ledgerSummary, formatMoney, addDailyGoal, toggleDailyGoalCircle, renameDailyGoalCircle, addDailyGoalCircle, removeDailyGoalCircle, setDailyMemo, setFixedDailyMemo, setDailyReview, clearSection };
});
